---
name: Actions en GitHub

on: push
jobs:
  run-github-actions :
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar el directorio
        run: |
          ls -la
      - name: checkout
        uses: actions/checkout@v2
      - name: Mostrar el directorio 2
        run: |
          ls -la
      - name: Crear Archivo Random
        run: |
          echo $RANDOM >> random.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add random.txt
          git commit -m "Añadido Random File"
          git push


      
