---
name: Comandos de shell
on : [push]
jobs:
  ejecutar-comandos-shell:
    runs-on: ubuntu-latest
    steps:
      - name: echo-cadena
        run: echo "Hello world"
      - name: scripts multilinea
        run: |
          node -v
          npm -v
          pwd
          cat /etc/os-release
  comandos-windows:
    runs-on: windows-latest
    steps: 
      - name: getLocation
        run: Get-Location
      - name: pwd
        run: pwd
        shell: bash

      